'use client';

import { useState, useEffect } from 'react';
import { FileCode, FileText, Image, FileSpreadsheet, Share2, Download, Eye } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useTrinityController } from '@/hooks/useTrinityController'; // Reusing for auth/context if needed, though this page specific data

interface Artifact {
    id: string;
    title: string;
    type: 'code' | 'document' | 'design' | 'report';
    content: string;
    agentId?: string;
    createdAt: string;
    shareCount: number;
    url?: string; // Add URL support for external artifacts
}

export default function ArtifactsPage() {
    const [artifacts, setArtifacts] = useState<Artifact[]>([]);
    const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchArtifacts();
    }, []);

    const fetchArtifacts = async () => {
        try {
            const { data, error } = await supabase
                .from('trinity_artifacts') // Assuming this table exists or mapping to it
                .select('*')
                .order('created_at', { ascending: false });

            if (error) throw error;

            // Map DB fields to UI Interface if necessary
            // Assuming DB has: id, title, type, content, created_at
            const mappedData = (data || []).map((item: any) => ({
                id: item.id,
                title: item.title || 'Untitled Artifact',
                type: (item.type || 'document') as Artifact['type'],
                content: item.content || '',
                createdAt: item.created_at,
                shareCount: 0, // Placeholder
                url: item.url
            }));

            setArtifacts(mappedData);
        } catch (error) {
            console.error('Error fetching artifacts:', error);
        } finally {
            setLoading(false);
        }
    };

    const shareArtifact = async (artifactId: string, e: React.MouseEvent) => {
        e.stopPropagation();
        // Placeholder share logic - simply copy link
        const shareUrl = `${window.location.origin}/artifacts/${artifactId}`;
        navigator.clipboard.writeText(shareUrl);
        alert('Share link copied to clipboard!'); // Could replace with toast later
    };

    const getTypeIcon = (type: string) => {
        switch (type) {
            case 'code':
                return FileCode;
            case 'document':
            case 'md':
            case 'markdown':
                return FileText;
            case 'design':
            case 'image':
                return Image;
            case 'report':
                return FileSpreadsheet;
            default:
                return FileText;
        }
    };

    const getTypeColor = (type: string) => {
        switch (type) {
            case 'code':
                return 'violet';
            case 'document':
            case 'md':
                return 'cyan';
            case 'design':
            case 'image':
                return 'pink';
            case 'report':
                return 'green';
            default:
                return 'gray';
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-96">
                <div className="w-16 h-16 border-4 border-violet-500/30 border-t-violet-500 rounded-full animate-spin" />
            </div>
        );
    }

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            {/* Header */}
            <div className="glass rounded-xl p-6 border border-white/10">
                <h2 className="text-2xl font-bold mb-2 text-white">Artifact Library</h2>
                <p className="text-gray-400 text-sm">
                    Digital assets generated by your autonomous swarm
                </p>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6">
                    {['code', 'document', 'design', 'report'].map((type) => {
                        const count = artifacts.filter((a) => a.type === type || (type === 'document' && a.type === 'md')).length;
                        const Icon = getTypeIcon(type);
                        const color = getTypeColor(type);
                        return (
                            <div key={type} className={`glass-light rounded-lg p-4 border border-${color}-500/30`}>
                                <div className={`text-${color}-400 mb-2`}>
                                    <Icon className="w-6 h-6" style={{ color: color === 'violet' ? '#a78bfa' : color === 'cyan' ? '#22d3ee' : color === 'pink' ? '#f472b6' : color === 'green' ? '#4ade80' : '#9ca3af' }} />
                                </div>
                                <div className="text-2xl font-bold mb-1 text-white">{count}</div>
                                <div className="text-xs text-gray-400 capitalize">{type}</div>
                            </div>
                        );
                    })}
                </div>
            </div>

            {/* Artifact Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {artifacts.length === 0 ? (
                    <div className="col-span-full flex flex-col items-center justify-center py-16 text-gray-500 glass rounded-xl border border-white/5">
                        <FileText className="w-12 h-12 mb-4 opacity-50" />
                        <p>No artifacts generated yet</p>
                    </div>
                ) : (
                    artifacts.map((artifact) => {
                        const Icon = getTypeIcon(artifact.type);
                        const color = getTypeColor(artifact.type);
                        const colorHex = color === 'violet' ? '#a78bfa' : color === 'cyan' ? '#22d3ee' : color === 'pink' ? '#f472b6' : color === 'green' ? '#4ade80' : '#9ca3af';

                        return (
                            <div
                                key={artifact.id}
                                className="glass rounded-xl p-5 border border-white/10 hover:border-violet-500/50 transition-all duration-300 group hover:-translate-y-1 hover:shadow-2xl"
                            >
                                {/* Header */}
                                <div className="flex items-start gap-4 mb-4">
                                    <div className={`p-3 glass-light rounded-lg border border-${color}-500/30 flex items-center justify-center`}>
                                        <Icon className="w-6 h-6" style={{ color: colorHex }} />
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <h3 className="font-semibold mb-1 truncate text-gray-100 group-hover:text-violet-400 transition-colors">
                                            {artifact.title}
                                        </h3>
                                        <div className="text-xs text-gray-500 capitalize">{artifact.type}</div>
                                    </div>
                                </div>

                                {/* Content Preview */}
                                <div className="glass-light rounded-lg p-3 mb-4 border border-white/5 h-24 overflow-hidden relative">
                                    <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/50 pointer-events-none" />
                                    <p className="text-xs text-gray-400 line-clamp-4 font-mono leading-relaxed">
                                        {artifact.content || 'No content preview available'}
                                    </p>
                                </div>

                                {/* Meta Info */}
                                <div className="flex items-center justify-between text-xs text-gray-500 mb-4 border-t border-white/5 pt-3">
                                    <span>{new Date(artifact.createdAt).toLocaleDateString()}</span>
                                    <div className="flex items-center gap-1">
                                        <Share2 className="w-3 h-3" />
                                        <span>{artifact.shareCount}</span>
                                    </div>
                                </div>

                                {/* Actions */}
                                <div className="flex gap-2">
                                    <button
                                        onClick={() => setSelectedArtifact(artifact)}
                                        className="flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg glass-light hover:bg-white/10 transition-colors text-sm font-medium text-gray-300 hover:text-white"
                                    >
                                        <Eye className="w-4 h-4" />
                                        View
                                    </button>
                                    <button
                                        onClick={(e) => shareArtifact(artifact.id, e)}
                                        className="flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg bg-violet-500/10 hover:bg-violet-500/20 border border-violet-500/30 transition-colors text-sm font-medium text-violet-300"
                                    >
                                        <Share2 className="w-4 h-4" />
                                        Share
                                    </button>
                                </div>
                            </div>
                        );
                    })
                )}
            </div>

            {/* Artifact Viewer Modal */}
            {selectedArtifact && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 animate-in fade-in duration-200">
                    <div
                        className="absolute inset-0 bg-black/80 backdrop-blur-md"
                        onClick={() => setSelectedArtifact(null)}
                    />
                    <div className="relative glass rounded-2xl p-6 w-full max-w-4xl border border-white/20 glow-violet max-h-[90vh] overflow-y-auto flex flex-col animate-in zoom-in-95 duration-300">
                        <div className="flex items-start justify-between mb-6 border-b border-white/10 pb-4">
                            <div>
                                <h3 className="text-2xl font-bold mb-2 text-white">{selectedArtifact.title}</h3>
                                <div className="flex items-center gap-3 text-sm text-gray-400">
                                    <span className="capitalize px-2 py-0.5 rounded-full bg-white/5 border border-white/10">{selectedArtifact.type}</span>
                                    <span>•</span>
                                    <span>{new Date(selectedArtifact.createdAt).toLocaleDateString()}</span>
                                </div>
                            </div>
                            <button
                                onClick={() => setSelectedArtifact(null)}
                                className="p-2 rounded-full hover:bg-white/10 transition-colors text-gray-400 hover:text-white"
                            >
                                ✕
                            </button>
                        </div>

                        <div className="glass-light rounded-lg p-6 border border-white/10 mb-6 flex-1 overflow-auto bg-[#0B0B0F]">
                            <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono leading-relaxed">
                                {selectedArtifact.content || 'No content available'}
                            </pre>
                        </div>

                        <div className="flex gap-3 justify-end pt-4 border-t border-white/10">
                            <button
                                onClick={(e) => shareArtifact(selectedArtifact.id, e)}
                                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-violet-600 hover:bg-violet-500 transition-colors text-white font-medium shadow-lg shadow-violet-500/20"
                            >
                                <Share2 className="w-4 h-4" />
                                Share Artifact
                            </button>
                            <button
                                onClick={() => {
                                    const blob = new Blob([selectedArtifact.content], { type: 'text/plain' });
                                    const url = URL.createObjectURL(blob);
                                    const a = document.createElement('a');
                                    a.href = url;
                                    a.download = `${selectedArtifact.title}.${selectedArtifact.type === 'code' ? 'txt' : 'md'}`;
                                    a.click();
                                }}
                                className="flex items-center gap-2 px-4 py-2 rounded-lg glass-light hover:bg-white/10 transition-colors text-gray-300 font-medium border border-white/10"
                            >
                                <Download className="w-4 h-4" />
                                Download
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
