import { useEffect, useState } from 'react';
import { FileCode, FileText, Image, FileSpreadsheet, Share2, Download, Eye } from 'lucide-react';
import { projectId, publicAnonKey } from '../utils/supabase/info';

interface Artifact {
  id: string;
  title: string;
  type: 'code' | 'document' | 'design' | 'report';
  content: string;
  agentId?: string;
  createdAt: string;
  shareCount: number;
}

export function Artifacts() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchArtifacts();
  }, []);

  const fetchArtifacts = async () => {
    try {
      const baseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-e172c8d9`;
      const response = await fetch(`${baseUrl}/artifacts`, {
        headers: { Authorization: `Bearer ${publicAnonKey}` },
      });
      const data = await response.json();

      if (data.success) {
        setArtifacts(data.data);
      }
      setLoading(false);
    } catch (error) {
      console.error('Error fetching artifacts:', error);
      setLoading(false);
    }
  };

  const shareArtifact = async (artifactId: string) => {
    try {
      const baseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-e172c8d9`;
      const response = await fetch(`${baseUrl}/artifacts/${artifactId}/share`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${publicAnonKey}` },
      });
      const data = await response.json();

      if (data.success) {
        setArtifacts(artifacts.map((a) => (a.id === artifactId ? data.data : a)));
        
        // Copy share link to clipboard
        const shareUrl = `${window.location.origin}/artifacts/${artifactId}`;
        navigator.clipboard.writeText(shareUrl);
        
        alert('Share link copied to clipboard!');
      }
    } catch (error) {
      console.error('Error sharing artifact:', error);
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'code':
        return FileCode;
      case 'document':
        return FileText;
      case 'design':
        return Image;
      case 'report':
        return FileSpreadsheet;
      default:
        return FileText;
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'code':
        return 'violet';
      case 'document':
        return 'cyan';
      case 'design':
        return 'pink';
      case 'report':
        return 'green';
      default:
        return 'gray';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="w-16 h-16 border-4 border-violet-500/30 border-t-violet-500 rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="glass rounded-xl p-6 border border-white/10">
        <h2 className="text-2xl font-bold mb-2">Artifact Library</h2>
        <p className="text-gray-400 text-sm">
          Digital assets generated by your autonomous swarm
        </p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6">
          {['code', 'document', 'design', 'report'].map((type) => {
            const count = artifacts.filter((a) => a.type === type).length;
            const Icon = getTypeIcon(type);
            const color = getTypeColor(type);
            return (
              <div key={type} className={`glass-light rounded-lg p-4 border border-${color}-500/30`}>
                <Icon className={`w-6 h-6 text-${color}-400 mb-2`} />
                <div className="text-2xl font-bold mb-1">{count}</div>
                <div className="text-xs text-gray-400 capitalize">{type}</div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Artifact Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {artifacts.length === 0 ? (
          <div className="col-span-full text-center py-12 text-gray-400">
            No artifacts generated yet
          </div>
        ) : (
          artifacts.map((artifact) => {
            const Icon = getTypeIcon(artifact.type);
            const color = getTypeColor(artifact.type);

            return (
              <div
                key={artifact.id}
                className="glass rounded-xl p-5 border border-white/10 hover:border-violet-500/50 transition-all duration-200 group"
              >
                {/* Header */}
                <div className="flex items-start gap-3 mb-4">
                  <div className={`p-3 glass-light rounded-lg border border-${color}-500/30`}>
                    <Icon className={`w-6 h-6 text-${color}-400`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold mb-1 truncate group-hover:text-violet-400 transition-colors">
                      {artifact.title}
                    </h3>
                    <div className="text-xs text-gray-400 capitalize">{artifact.type}</div>
                  </div>
                </div>

                {/* Content Preview */}
                <div className="glass-light rounded-lg p-3 mb-4 border border-white/5">
                  <p className="text-xs text-gray-400 line-clamp-3 font-mono">
                    {artifact.content || 'No content preview available'}
                  </p>
                </div>

                {/* Meta Info */}
                <div className="flex items-center justify-between text-xs text-gray-500 mb-4">
                  <span>{new Date(artifact.createdAt).toLocaleDateString()}</span>
                  <div className="flex items-center gap-1">
                    <Share2 className="w-3 h-3" />
                    <span>{artifact.shareCount} shares</span>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex gap-2">
                  <button
                    onClick={() => setSelectedArtifact(artifact)}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg glass-light hover:bg-white/10 transition-colors text-sm"
                  >
                    <Eye className="w-4 h-4" />
                    View
                  </button>
                  <button
                    onClick={() => shareArtifact(artifact.id)}
                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 rounded-lg bg-violet-500/20 hover:bg-violet-500/30 border border-violet-500/50 transition-colors text-sm"
                  >
                    <Share2 className="w-4 h-4" />
                    Share
                  </button>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Artifact Viewer Modal */}
      {selectedArtifact && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="absolute inset-0 bg-black/70 backdrop-blur-md"
            onClick={() => setSelectedArtifact(null)}
          />
          <div className="relative glass rounded-2xl p-6 w-full max-w-3xl border border-white/20 glow-violet max-h-[90vh] overflow-y-auto">
            <div className="flex items-start justify-between mb-6">
              <div>
                <h3 className="text-2xl font-bold mb-2">{selectedArtifact.title}</h3>
                <div className="flex items-center gap-3 text-sm text-gray-400">
                  <span className="capitalize">{selectedArtifact.type}</span>
                  <span>•</span>
                  <span>{new Date(selectedArtifact.createdAt).toLocaleDateString()}</span>
                  <span>•</span>
                  <span>{selectedArtifact.shareCount} shares</span>
                </div>
              </div>
              <button
                onClick={() => setSelectedArtifact(null)}
                className="p-2 rounded-lg hover:bg-white/10 transition-colors"
              >
                ✕
              </button>
            </div>

            <div className="glass-light rounded-lg p-6 border border-white/10 mb-6">
              <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono">
                {selectedArtifact.content || 'No content available'}
              </pre>
            </div>

            <div className="flex gap-2">
              <button
                onClick={() => shareArtifact(selectedArtifact.id)}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-violet-500 hover:bg-violet-600 transition-colors"
              >
                <Share2 className="w-4 h-4" />
                Share
              </button>
              <button
                onClick={() => {
                  const blob = new Blob([selectedArtifact.content], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `${selectedArtifact.title}.txt`;
                  a.click();
                }}
                className="flex items-center gap-2 px-4 py-2 rounded-lg glass-light hover:bg-white/10 transition-colors"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
