-- Create the trinity_retros table for Strategy 10: Reflection and Retrospectives
create table if not exists public.trinity_retros (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  agent text not null,
  reflection text not null, -- Full reflection text generated by LLM
  successes text, -- Optional structured field
  failures text, -- Optional structured field
  lessons text -- Optional structured field
);

-- Enable Row Level Security (RLS)
alter table public.trinity_retros enable row level security;

-- Allow authenticated users (agents) to insert
create policy "Agents can insert retrospectives"
  on public.trinity_retros
  for insert
  to authenticated
  with check (true);

-- Allow authenticated users (agents/dashboard) to read
create policy "Enable read access for all users"
  on public.trinity_retros
  for select
  using (true);
